Make automatic release builds
Adds a script to run the complete automated release workflow as the last
step of the release workflow. This step is only ever run manually, and
only uploads to the correct location when running a full release build
(with GROMACS_RELEASE == true) on one of the branches we do releases
from (master, release-2022).

diff --git a/admin/gitlab-ci/archive.gitlab-ci.yml b/admin/gitlab-ci/archive.gitlab-ci.yml
--- a/admin/gitlab-ci/archive.gitlab-ci.yml
+++ b/admin/gitlab-ci/archive.gitlab-ci.yml
@@ -304,20 +304,32 @@ archive:nightly-webpage:
 archive:full-release:
   extends:
     - .webpage:build
-    - .rules:nightly-only-for-release
+    - .rules:nightly-only-for-release-manual
   stage: release-deploy
   dependencies:
     - webpage:build:release
     - archive:package
     - regressiontests:package
+    - prepare-release-version
   variables:
     BUILD_DIR: release-doc-builds
+  before_script:
+    - if [[ -z $SSH_PRIVATE_KEY ]] ; then
+        echo "Error Private key is not defined, not running script" ;
+        exit 1;
+      fi
+    - if [[ -z $SSH_KNOWN_HOSTS ]] ; then
+        echo "Error Known hosts is not defined, not running script" ;
+        exit 1;
+      fi
+    - eval $(ssh-agent -s)
+    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+    - mkdir -p ~/.ssh
+    - chmod 700 ~/.ssh
+    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts # Force overwrite the known hosts so we only have the keys we need in it.
+    - chmod 644 ~/.ssh/known_hosts
   script:
-    - tar czf webpage.tar.gz $BUILD_DIR/docs/html/
-  artifacts:
-    when: always
-    paths:
-      - webpage.tar.gz
-      - gromacs-*tar.gz
-      - regressiontests-*tar.gz
+    - export VERSION=`cat version.json |
+      python3 -c "import json,sys; print(json.load(sys.stdin)['version'])"`
+    - bash admin/ci-scripts/upload-release-artefacts.sh
 
